### ISSUE TITLE
[Mod incompatible]bucket fish that shouldn’t be there

### ISSUE THREAD

**Issue by zeng-github01** [jbredwards/Subaquatic#75] opened 2024-03-03 04:17 UTC
After installing Nuclear Craft, fish will appear in the chemical bucket

Normally it should only appear in  water bucket

Fish in a Bucket Molten Gelatin and Bucket Preheated Water

**Comment by jbredwards** [comment] 2024-11-30 14:43
duplicate of #5

**Closed as completed by jbredwards** 2024-11-30 14:43 UTC
