### ISSUE TITLE
AssetMover Crash / Missing Textures

### ISSUE THREAD

**Issue by Guinnedog** [jbredwards/Subaquatic#52] opened 2023-07-12 13:47 UTC
I don't quite know how to read crashlogs, but It looks like the mod may be incompatible with another resulting in a crash on start up.

[crash-2023-07-12_06.40.36-client.txt](https://github.com/jbredwards/Subaquatic/files/12028627/crash-2023-07-12_06.40.36-client.txt)

**Comment by Guinnedog** [comment] 2023-07-12 13:59
I have also encountered a problem where nothing seems to have textures and are all just colored checkered squares
![2023-07-12_06 55 03](https://github.com/jbredwards/Subaquatic/assets/128102615/e66d7f54-0bb8-4203-bc2c-47fe8492a286)

**Comment by jbredwards** [comment] 2023-07-12 14:14
duplicate of #43

**Closed as completed by jbredwards** 2023-07-12 14:14 UTC
Labels: duplicate
