### ISSUE TITLE
Another Nothirium issue.

### ISSUE THREAD

**Issue by MagmaSlime123** [jbredwards/Subaquatic#54] opened 2023-07-22 19:34 UTC
See https://github.com/Meldexun/Nothirium/issues/76.

**Comment by jbredwards** [comment] 2023-07-22 19:43
duplicate of https://github.com/jbredwards/Subaquatic/issues/33, update to v1.2.0 (which can be downloaded [here](https://modrinth.com/mod/subaquatic))

**Closed as completed by jbredwards** 2023-07-22 19:43 UTC
Labels: invalid

**Comment by MagmaSlime123** [comment] 2023-07-22 19:51
Didn't know you posted onto Modrinth. My bad.
