### ISSUE TITLE
Crash at startup 

### ISSUE THREAD

**Issue by juraj-hrivnak** [jbredwards/Subaquatic#43] opened 2023-06-04 16:41 UTC
The textures didn't download properly for some reason.
Debug log: https://mclo.gs/z8apUji#L17144
Subaquatic: v1.1.0-mc1.12.2
AssetMover: 2.5

**Comment by jbredwards** [comment] 2023-06-05 01:00
duplicate of https://github.com/CleanroomMC/AssetMover/issues/12

**Closed as completed by jbredwards** 2023-06-05 01:00 UTC
Labels: wontfix
