### ISSUE TITLE
Solid water (not sure what this is) on top of kelp and seagrass. Most blocks have no sound either.

### ISSUE THREAD

**Issue by MagmaSlime123** [jbredwards/Subaquatic#2] opened 2023-02-13 23:28 UTC
Title. (If FluidloggedAPI is the cause, you can report it to them, your the one who requires it.)

![2023-02-13_16 24 45](https://user-images.githubusercontent.com/51277766/218597432-b85db05d-37a5-4751-8254-f46d8f546ad7.png)

**Comment by jbredwards** [comment] 2023-02-15 04:49
The kelp visual bug is caused by a fluidlogged api conflict with better foliage, which I'll fix when I get around to updating that mod. Can you send your logs? I have no clue what could be causing the block sound bug since it's working fine for me.

**Comment by MagmaSlime123** [comment] 2023-02-15 05:39
I've tested with no other mods, same issue on the block sounds.

**Comment by jbredwards** [comment] 2023-05-26 18:16
Does this still happen with v1.1.0?

**Comment by MagmaSlime123** [comment] 2023-05-26 18:49
No apparently. This mod hasn't been updated in quite a while, so I haven't been paying much attention lately.

**Comment by jbredwards** [comment] 2023-05-26 18:54
nice, marking this as fixed then :). If it comes up again, I'll reopen the issue

**Closed as completed by jbredwards** 2023-05-26 18:54 UTC
Labels: bug
